CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE organizations (id text PRIMARY KEY, name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE users (id text PRIMARY KEY, organization_id text NOT NULL REFERENCES organizations(id), email text NOT NULL, password_hash text NOT NULL, display_name text NOT NULL, active boolean NOT NULL DEFAULT true, mfa_required boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (organization_id,email));
CREATE TABLE sessions (id_hash text PRIMARY KEY, user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, organization_id text NOT NULL REFERENCES organizations(id), csrf_hash text NOT NULL, expires_at timestamptz NOT NULL, revoked_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), last_seen_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE mfa_secrets (user_id text PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, ciphertext text NOT NULL, nonce text NOT NULL, key_version integer NOT NULL, enabled_at timestamptz);
CREATE TABLE recovery_codes (id text PRIMARY KEY, user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, code_hash text NOT NULL, used_at timestamptz, UNIQUE(user_id,code_hash));
CREATE TABLE roles (id text PRIMARY KEY, name text NOT NULL UNIQUE);
CREATE TABLE permissions (id text PRIMARY KEY, name text NOT NULL UNIQUE);
CREATE TABLE user_roles (user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE, role_id text NOT NULL REFERENCES roles(id), PRIMARY KEY(user_id,role_id));
CREATE TABLE role_permissions (role_id text NOT NULL REFERENCES roles(id) ON DELETE CASCADE, permission_id text NOT NULL REFERENCES permissions(id), PRIMARY KEY(role_id,permission_id));

CREATE TABLE sites (id text PRIMARY KEY, organization_id text NOT NULL REFERENCES organizations(id), name text NOT NULL, type text NOT NULL, region text, description text, UNIQUE(organization_id,name));
CREATE TABLE owners (id text PRIMARY KEY, organization_id text NOT NULL REFERENCES organizations(id), name text NOT NULL, email text, team text, type text NOT NULL);
CREATE TABLE tags (id text PRIMARY KEY, organization_id text NOT NULL REFERENCES organizations(id), name text NOT NULL, UNIQUE(organization_id,name));
CREATE TABLE assets (id text PRIMARY KEY, organization_id text NOT NULL REFERENCES organizations(id), canonical_name text NOT NULL, display_name text NOT NULL, asset_type text NOT NULL, status text NOT NULL, environment text, site_id text REFERENCES sites(id), criticality text NOT NULL DEFAULT 'NORMAL', owner_id text REFERENCES owners(id), first_seen_at timestamptz NOT NULL, last_seen_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), retired_at timestamptz, CHECK(status IN ('ACTIVE','STALE','MISSING','CONFLICTING','RETIRED','UNKNOWN')));
CREATE INDEX assets_org_status_idx ON assets(organization_id,status);
CREATE INDEX assets_org_type_idx ON assets(organization_id,asset_type);
CREATE INDEX assets_canonical_trgm_idx ON assets USING gin(canonical_name gin_trgm_ops);
CREATE INDEX assets_display_trgm_idx ON assets USING gin(display_name gin_trgm_ops);
CREATE TABLE asset_tags (asset_id text NOT NULL REFERENCES assets(id) ON DELETE CASCADE, tag_id text NOT NULL REFERENCES tags(id) ON DELETE CASCADE, PRIMARY KEY(asset_id,tag_id));
CREATE TABLE custom_field_schemas (id text PRIMARY KEY, organization_id text NOT NULL REFERENCES organizations(id), name text NOT NULL, field_type text NOT NULL, enum_values jsonb, required boolean NOT NULL DEFAULT false, limits jsonb NOT NULL DEFAULT '{}', UNIQUE(organization_id,name));
CREATE TABLE custom_field_values (asset_id text NOT NULL REFERENCES assets(id) ON DELETE CASCADE, schema_id text NOT NULL REFERENCES custom_field_schemas(id) ON DELETE CASCADE, value jsonb NOT NULL, PRIMARY KEY(asset_id,schema_id));

CREATE TABLE collectors (id text PRIMARY KEY, organization_id text NOT NULL REFERENCES organizations(id), name text NOT NULL, public_key bytea NOT NULL, fingerprint text NOT NULL, status text NOT NULL, collector_version text, protocol_version text, compatibility_status text NOT NULL DEFAULT 'UNKNOWN', os text, architecture text, capabilities jsonb NOT NULL DEFAULT '[]', last_heartbeat_at timestamptz, enrolled_at timestamptz NOT NULL DEFAULT now(), revoked_at timestamptz, UNIQUE(organization_id,fingerprint));
CREATE TABLE collector_credentials (id text PRIMARY KEY, organization_id text NOT NULL REFERENCES organizations(id), collector_id text NOT NULL REFERENCES collectors(id), credential_hash text NOT NULL, expires_at timestamptz, revoked_at timestamptz);
CREATE TABLE collector_enrollment_tokens (id text PRIMARY KEY, organization_id text NOT NULL REFERENCES organizations(id), token_hash text NOT NULL UNIQUE, created_by text NOT NULL REFERENCES users(id), expires_at timestamptz NOT NULL, used_at timestamptz, scope text NOT NULL DEFAULT 'collector.enroll');
CREATE TABLE infrastructure_connectors (id text PRIMARY KEY, organization_id text NOT NULL REFERENCES organizations(id), collector_id text REFERENCES collectors(id), name text NOT NULL, type text NOT NULL, environment text, enabled boolean NOT NULL DEFAULT true, authoritative_level text NOT NULL, configuration jsonb NOT NULL DEFAULT '{}', credential_reference text, sync_interval interval, stale_after interval, last_successful_sync_at timestamptz, last_attempt_at timestamptz, last_status text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE evidence_artifacts (id text PRIMARY KEY, organization_id text NOT NULL REFERENCES organizations(id), object_key text NOT NULL, content_hash text NOT NULL, size_bytes bigint NOT NULL, media_type text NOT NULL, status text NOT NULL, expires_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(organization_id,object_key));
CREATE TABLE source_snapshots (id text PRIMARY KEY, organization_id text NOT NULL REFERENCES organizations(id), connector_id text NOT NULL REFERENCES infrastructure_connectors(id), collector_id text REFERENCES collectors(id), status text NOT NULL, sequence bigint NOT NULL, started_at timestamptz NOT NULL, completed_at timestamptz, asset_count integer NOT NULL DEFAULT 0, relationship_count integer NOT NULL DEFAULT 0, content_hash text NOT NULL, raw_artifact_id text REFERENCES evidence_artifacts(id), error_summary text, protocol_version text, UNIQUE(organization_id,connector_id,sequence), UNIQUE(organization_id,connector_id,content_hash));
CREATE TABLE asset_source_identities (id text PRIMARY KEY, organization_id text NOT NULL REFERENCES organizations(id), asset_id text NOT NULL REFERENCES assets(id), connector_id text NOT NULL REFERENCES infrastructure_connectors(id), external_id text NOT NULL, external_type text, first_seen_at timestamptz NOT NULL, last_seen_at timestamptz NOT NULL, status text NOT NULL, UNIQUE(organization_id,connector_id,external_id));
CREATE INDEX asset_identity_external_trgm_idx ON asset_source_identities USING gin(external_id gin_trgm_ops);
CREATE TABLE asset_observations (id text PRIMARY KEY, organization_id text NOT NULL REFERENCES organizations(id), snapshot_id text NOT NULL REFERENCES source_snapshots(id), connector_id text NOT NULL REFERENCES infrastructure_connectors(id), collector_id text REFERENCES collectors(id), external_id text NOT NULL, asset_type text NOT NULL, observed_at timestamptz NOT NULL, attributes jsonb NOT NULL, identity_hints jsonb NOT NULL, fingerprint text NOT NULL, status text NOT NULL, UNIQUE(snapshot_id,external_id));
CREATE TABLE asset_attribute_claims (id text PRIMARY KEY, organization_id text NOT NULL REFERENCES organizations(id), asset_id text NOT NULL REFERENCES assets(id), attribute_key text NOT NULL, value jsonb NOT NULL, connector_id text NOT NULL REFERENCES infrastructure_connectors(id), snapshot_id text NOT NULL REFERENCES source_snapshots(id), observed_at timestamptz NOT NULL, authority text NOT NULL, confidence text NOT NULL, active boolean NOT NULL DEFAULT true);
CREATE INDEX claims_asset_key_active_idx ON asset_attribute_claims(organization_id,asset_id,attribute_key) WHERE active;

CREATE TABLE asset_relationships (id text PRIMARY KEY, organization_id text NOT NULL REFERENCES organizations(id), from_asset_id text NOT NULL REFERENCES assets(id), to_asset_id text NOT NULL REFERENCES assets(id), type text NOT NULL, status text NOT NULL, first_seen_at timestamptz NOT NULL, last_seen_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(organization_id,from_asset_id,to_asset_id,type));
CREATE INDEX relationships_from_idx ON asset_relationships(organization_id,from_asset_id,status);
CREATE INDEX relationships_to_idx ON asset_relationships(organization_id,to_asset_id,status);
CREATE TABLE relationship_observations (id text PRIMARY KEY, organization_id text NOT NULL REFERENCES organizations(id), relationship_id text REFERENCES asset_relationships(id), snapshot_id text NOT NULL REFERENCES source_snapshots(id), connector_id text NOT NULL REFERENCES infrastructure_connectors(id), external_from_id text NOT NULL, external_to_id text NOT NULL, type text NOT NULL, observed_at timestamptz NOT NULL, attributes jsonb NOT NULL, UNIQUE(snapshot_id,external_from_id,external_to_id,type));
CREATE TABLE asset_merge_candidates (id text PRIMARY KEY, organization_id text NOT NULL REFERENCES organizations(id), asset_a text NOT NULL REFERENCES assets(id), asset_b text NOT NULL REFERENCES assets(id), confidence text NOT NULL, reasons jsonb NOT NULL, status text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), reviewed_at timestamptz, reviewed_by text REFERENCES users(id));
CREATE TABLE asset_merge_history (id text PRIMARY KEY, organization_id text NOT NULL REFERENCES organizations(id), retained_asset_id text NOT NULL REFERENCES assets(id), merged_asset_id text NOT NULL REFERENCES assets(id), evidence jsonb NOT NULL, merged_by text NOT NULL REFERENCES users(id), merged_at timestamptz NOT NULL DEFAULT now(), reversed_at timestamptz, reversed_by text REFERENCES users(id));

CREATE TABLE reconciliation_policies (id text PRIMARY KEY, organization_id text NOT NULL REFERENCES organizations(id), connector_id text REFERENCES infrastructure_connectors(id), asset_type text, attribute_key text, relationship_type text, authority text NOT NULL, precedence integer NOT NULL, missing_success_threshold integer NOT NULL DEFAULT 2, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE reconciliation_runs (id text PRIMARY KEY, organization_id text NOT NULL REFERENCES organizations(id), connector_id text NOT NULL REFERENCES infrastructure_connectors(id), snapshot_id text NOT NULL REFERENCES source_snapshots(id), status text NOT NULL, started_at timestamptz NOT NULL, completed_at timestamptz, assets_created integer NOT NULL DEFAULT 0, assets_updated integer NOT NULL DEFAULT 0, assets_unchanged integer NOT NULL DEFAULT 0, assets_missing integer NOT NULL DEFAULT 0, assets_conflicting integer NOT NULL DEFAULT 0, relationships_created integer NOT NULL DEFAULT 0, relationships_updated integer NOT NULL DEFAULT 0, relationships_removed integer NOT NULL DEFAULT 0, change_events_created integer NOT NULL DEFAULT 0, summary jsonb NOT NULL DEFAULT '{}', UNIQUE(snapshot_id));
CREATE TABLE infrastructure_changes (id text PRIMARY KEY, organization_id text NOT NULL REFERENCES organizations(id), asset_id text REFERENCES assets(id), relationship_id text REFERENCES asset_relationships(id), change_type text NOT NULL, before_value jsonb, after_value jsonb, source text NOT NULL, detected_at timestamptz NOT NULL, summary text NOT NULL, confidence text NOT NULL, logical_identity text NOT NULL, UNIQUE(organization_id,logical_identity));
CREATE TABLE infrastructure_findings (id text PRIMARY KEY, organization_id text NOT NULL REFERENCES organizations(id), asset_id text REFERENCES assets(id), finding_type text NOT NULL, status text NOT NULL, priority text NOT NULL, explanation text NOT NULL, logical_identity text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(organization_id,logical_identity));

CREATE TABLE imports (id text PRIMARY KEY, organization_id text NOT NULL REFERENCES organizations(id), type text NOT NULL, status text NOT NULL, idempotency_key text NOT NULL, artifact_id text REFERENCES evidence_artifacts(id), preview jsonb, error_summary text, created_by text NOT NULL REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(organization_id,idempotency_key));
CREATE TABLE exports (id text PRIMARY KEY, organization_id text NOT NULL REFERENCES organizations(id), type text NOT NULL, status text NOT NULL, idempotency_key text NOT NULL, artifact_id text REFERENCES evidence_artifacts(id), created_by text NOT NULL REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz, UNIQUE(organization_id,idempotency_key));
CREATE TABLE audit_events (id text PRIMARY KEY, organization_id text NOT NULL REFERENCES organizations(id), actor_id text, action text NOT NULL, resource_type text, resource_id text, request_id text, payload jsonb NOT NULL, previous_hash text NOT NULL, event_hash text NOT NULL, occurred_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX audit_org_time_idx ON audit_events(organization_id,occurred_at DESC);
CREATE TABLE scheduler_leases (name text PRIMARY KEY, owner_id text NOT NULL, leased_until timestamptz NOT NULL, updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE secret_metadata (id text PRIMARY KEY, organization_id text NOT NULL REFERENCES organizations(id), purpose text NOT NULL, ciphertext text NOT NULL, nonce text NOT NULL, key_version integer NOT NULL, metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), rotated_at timestamptz);
CREATE TABLE collector_jobs (id text PRIMARY KEY, organization_id text NOT NULL REFERENCES organizations(id), collector_id text NOT NULL REFERENCES collectors(id), connector_id text NOT NULL REFERENCES infrastructure_connectors(id), status text NOT NULL, scheduled_at timestamptz NOT NULL, leased_until timestamptz, attempts integer NOT NULL DEFAULT 0, result jsonb, UNIQUE(connector_id,scheduled_at));

INSERT INTO roles(id,name) VALUES ('role-owner','OWNER'),('role-admin','ADMIN'),('role-infra-admin','INFRA_ADMIN'),('role-asset-manager','ASSET_MANAGER'),('role-operator','OPERATOR'),('role-auditor','AUDITOR'),('role-viewer','VIEWER');
INSERT INTO permissions(id,name) SELECT 'permission-'||replace(p,'.','-'),p FROM unnest(ARRAY['asset.read','asset.manage','asset.merge','connector.read','connector.manage','connector.run','collector.read','collector.manage','policy.read','policy.manage','finding.read','finding.manage','import.run','export.run','audit.read','user.manage','settings.manage']) p;
INSERT INTO role_permissions(role_id,permission_id) SELECT 'role-owner',id FROM permissions;

